//Get Articles
export const FETCH_ARTICLES_STARTED = 'FETCH_ARTICLES_STARTED';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED';

export const SET_PAGE = 'SET_PAGE';
export const TOGGLE_FULL_ARTICLE = 'TOGGLE_FULL_ARTICLE';
export const INPUT_CHANGED = 'INPUT_CHANGED';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGED_SEARCH_TERM = 'CHANGED_SEARCH_TERM'

export const CREATE_TOAST_MESSAGE = 'CREATE_TOAST_MESSAGE';
export const REMOVE_TOAST_MESSAGE = 'REMOVE_TOAST_MESSAGE';

//SAGA_FUNCTIONS
//Articles
export const FIND_ARTICLES = 'FIND_ARTICLES';

//Toasts
export const NEW_TOAST = 'NEW_TOAST'

//Errors
export const ERROR_OCCURERED = 'ERROR_OCCURERED'

//REQUESTS
export const FETCH_REQUEST_STARTED = 'FETCH_REQUEST_STARTED'
export const FETCH_REQUEST_FINISHED = 'FETCH_REQUEST_FINISHED'

export const INFINITE_SCROLL_REQUEST_STARTED = 'INFINITE_SCROLL_REQUEST_STARTED'
export const INFINITE_SCROLL_REQUEST_FINISHED = 'INFINITE_SCROLL_FINISHED'

export const PAGINATION_REQUEST_STARTED = 'PAGINATION_REQUEST_STARTED'
export const PAGINATION_REQUEST_FINISHED = 'PAGINATION_REQUEST_FINISHED'