//Get Articles
export const FETCH_ARTICLES_STARTED = 'FETCH_ARTICLES_STARTED';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED';

//Page actions
export const SET_PAGE = 'SET_PAGE';
export const TOGGLE_FULL_ARTICLE = 'TOGGLE_FULL_ARTICLE';
export const INPUT_CHANGED = 'INPUT_CHANGED';
export const CHANGE_PAGE = 'CHANGE_PAGE';

//Toasts
export const CREATE_TOAST = 'CREATE_TOAST'
export const REMOVE_TOAST = 'REMOVE_TOAST'
